/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hype GLK
 */
public class tugas5 extends javax.swing.JFrame {

    /**
     * Creates new form tugas5
     */
    public tugas5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CbMakanan = new javax.swing.JLabel();
        CbMinuman = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaResume = new javax.swing.JTextArea();
        CbNama = new javax.swing.JTextField();
        CbAlamat = new javax.swing.JTextField();
        eMieAyam = new javax.swing.JRadioButton();
        eMieGoreng = new javax.swing.JRadioButton();
        eBuburAyam = new javax.swing.JRadioButton();
        eDimsum = new javax.swing.JRadioButton();
        eTehManis = new javax.swing.JRadioButton();
        eJusAlpukat = new javax.swing.JRadioButton();
        eKopi = new javax.swing.JRadioButton();
        eSoda = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        CbMakanan.setText("Makanan");

        CbMinuman.setText("Minuman");

        jLabel5.setText("Resume");

        AreaResume.setColumns(20);
        AreaResume.setRows(5);
        jScrollPane1.setViewportView(AreaResume);

        CbNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbNamaActionPerformed(evt);
            }
        });

        CbAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbAlamatActionPerformed(evt);
            }
        });

        eMieAyam.setText("Mie Ayam");

        eMieGoreng.setText("Mie Goreng");
        eMieGoreng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eMieGorengActionPerformed(evt);
            }
        });

        eBuburAyam.setText("Bubur Ayam");

        eDimsum.setText("Dimsum");

        eTehManis.setText("Teh manis");

        eJusAlpukat.setText("Jus Alpukat");
        eJusAlpukat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJusAlpukatActionPerformed(evt);
            }
        });

        eKopi.setText("Kopi");
        eKopi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eKopiActionPerformed(evt);
            }
        });

        eSoda.setText("Soda");

        jButton1.setText("PESAN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CbMinuman)
                            .addComponent(CbMakanan))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(eMieGoreng)
                                            .addComponent(CbAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(124, 124, 124)
                                        .addComponent(jButton1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(eJusAlpukat)
                                        .addGap(22, 22, 22)
                                        .addComponent(eSoda)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eMieAyam)
                            .addComponent(eTehManis))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eKopi)
                            .addComponent(eDimsum)
                            .addComponent(eBuburAyam))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(CbNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(CbAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMieAyam)
                    .addComponent(eBuburAyam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbMakanan)
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMieGoreng)
                    .addComponent(eDimsum))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eTehManis)
                                    .addComponent(eKopi))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eJusAlpukat)
                            .addComponent(eSoda))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(CbMinuman)
                        .addGap(82, 82, 82))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eKopiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eKopiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eKopiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int IndexCombo;
        
        String DaftarMakanan="";
        String DaftarMinuman="";
        
        
        if (eMieAyam.isSelected()) {
            DaftarMakanan += eMieAyam.getText() + "";
        }
        if (eBuburAyam.isSelected()) {
            DaftarMakanan += eBuburAyam.getText() + "";
        }
        if (eMieGoreng.isSelected()) {
            DaftarMakanan += eMieGoreng.getText() + "";
        }
        if (eDimsum.isSelected()) {
            DaftarMakanan += eDimsum.getText() + "";
        }
        
        if (eTehManis.isSelected()) {
            DaftarMinuman += eTehManis.getText() + "";
        }
        if (eKopi.isSelected()) {
            DaftarMinuman += eKopi.getText() + "";
        }
        if (eJusAlpukat.isSelected()) {
            DaftarMinuman += eJusAlpukat.getText() + "";
        }
        if (eSoda.isSelected()) {
            DaftarMinuman += eSoda.getText() + "";
        }
        
        AreaResume.setText(
                 "NAMA :\t" + CbNama.getText() + "\n"+
                 "ALAMAT :\t" + CbAlamat.getText() + "\n"+
                 "MINUMAN :\t" + DaftarMinuman + "\n"+
                 "MAKANAN :\t" + DaftarMakanan + "\n"
        );
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void eMieGorengActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eMieGorengActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eMieGorengActionPerformed

    private void eJusAlpukatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJusAlpukatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eJusAlpukatActionPerformed

    private void CbNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbNamaActionPerformed

    private void CbAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbAlamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaResume;
    private javax.swing.JTextField CbAlamat;
    private javax.swing.JLabel CbMakanan;
    private javax.swing.JLabel CbMinuman;
    private javax.swing.JTextField CbNama;
    private javax.swing.JRadioButton eBuburAyam;
    private javax.swing.JRadioButton eDimsum;
    private javax.swing.JRadioButton eJusAlpukat;
    private javax.swing.JRadioButton eKopi;
    private javax.swing.JRadioButton eMieAyam;
    private javax.swing.JRadioButton eMieGoreng;
    private javax.swing.JRadioButton eSoda;
    private javax.swing.JRadioButton eTehManis;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
